title: "Rothbardinstitutet"
author: "Rothbardinstitutet"
description: "<i>Fiat justitia, ne pereat mundus</i>"
permalink: /:title/
lang: "sv"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

sidebar: true               # show a sidebar instead of the usual header
show_excerpts: true         # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_title: true            # always keep the site title visible

# Styling

dark_header: true           # always keep the header dark
minimal: false               # use simpler style

# Menu

navigation:
  - {file: "index.html"}
  - {file: "about.md", title: Om institutet}
  - {file: "murray-rothbard.md"}
  - {file: "libertarianism.md"}
  - {file: "osterrikiska-skolan.md"}
  - {file: "archive.html"}
  - {file: "authors.html"}

external:                    # see http://fontawesome.com/icons
  - {title: Twitter, url: "https://twitter.com/rothbard_se"}
#  - {title: Prenumerera, icon: rss, url: "/feed.xml"}

 # - {title: YouTube, icon: youtube, url: "https://www.youtube.com/channel/UCQq-s5zMM3_G7SxeFGeXyuQ"}
 # - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
 # - {title: Github, icon: github, url: "https://github.com/Rothbardinstitutet"}

comments:
  disqus_shortname: "rothbardinstitutet"
#  isso_domain: ""           # see https://posativ.org/isso/

collections:
  authors:
    output: true
  categories:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
 - jekyll-feed
